export const errorCodes = `export const ERROR_CODE = {
  // Generic
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  UNKNOWN_THROWN_VALUE: 'UNKNOWN_THROWN_VALUE',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  OPERATION_FAILED: 'OPERATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_JSON: 'INVALID_JSON',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  FIELD_TOO_LONG: 'FIELD_TOO_LONG',
  FIELD_TOO_SHORT: 'FIELD_TOO_SHORT',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_TYPE: 'INVALID_TYPE',
  OUT_OF_RANGE: 'OUT_OF_RANGE',
  VALUE_NOT_ALLOWED: 'VALUE_NOT_ALLOWED',
  DUPLICATE_VALUE: 'DUPLICATE_VALUE',

  // Authorization & Authentication
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MISSING_TOKEN: 'MISSING_TOKEN',
  EXPIRED_TOKEN: 'EXPIRED_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCESS_BLOCKED: 'ACCESS_BLOCKED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',
  FORBIDDEN: 'FORBIDDEN',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  RESOURCE_DISABLED: 'RESOURCE_DISABLED',
  RESOURCE_DELETED: 'RESOURCE_DELETED',

  // System
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Persistence
  DATA_READ_ERROR: 'DATA_READ_ERROR',
  DATA_WRITE_ERROR: 'DATA_WRITE_ERROR',
  DATA_INTEGRITY_ERROR: 'DATA_INTEGRITY_ERROR',
  DATA_CONSTRAINT_VIOLATION: 'DATA_CONSTRAINT_VIOLATION',
  DATA_CONFLICT: 'DATA_CONFLICT',

  // Security
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',
  CSRF_DETECTED: 'CSRF_DETECTED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  REQUEST_BLOCKED: 'REQUEST_BLOCKED',

  // Operations
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  INVALID_OPERATION_STATE: 'INVALID_OPERATION_STATE',
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',

  // Files
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',

  // Notifications
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',

  // Session
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_INVALID: 'SESSION_INVALID',
  CLIENT_STATE_INVALID: 'CLIENT_STATE_INVALID',

  // Environment
  CONFIG_MISSING: 'CONFIG_MISSING',
  CONFIG_INVALID: 'CONFIG_INVALID',
  ENVIRONMENT_ERROR: 'ENVIRONMENT_ERROR'
} as const

export type ErrorCode = keyof typeof ERROR_CODE
  `