export const statusMap = `import { ERROR_CODE, type ErrorCode } from './errorCodes.js'

export const ErrorStatus: Record<ErrorCode, number> = {
  // Generic
  [ERROR_CODE.UNKNOWN_ERROR]: 500,
  [ERROR_CODE.INTERNAL_ERROR]: 500,
  [ERROR_CODE.UNEXPECTED_ERROR]: 500,
  [ERROR_CODE.UNKNOWN_THROWN_VALUE]: 500,
  [ERROR_CODE.NOT_IMPLEMENTED]: 501,
  [ERROR_CODE.OPERATION_FAILED]: 500,
  [ERROR_CODE.NOT_FOUND]: 404,
  [ERROR_CODE.ROUTE_NOT_FOUND]: 404,
  [ERROR_CODE.DUPLICATE_ENTRY]: 409,
  [ERROR_CODE.ALREADY_EXISTS]: 409,

  // Validation
  [ERROR_CODE.VALIDATION_ERROR]: 400,
  [ERROR_CODE.INVALID_INPUT]: 400,
  [ERROR_CODE.INVALID_JSON]: 400,
  [ERROR_CODE.REQUIRED_FIELD_MISSING]: 400,
  [ERROR_CODE.FIELD_TOO_LONG]: 400,
  [ERROR_CODE.FIELD_TOO_SHORT]: 400,
  [ERROR_CODE.INVALID_FORMAT]: 400,
  [ERROR_CODE.INVALID_TYPE]: 400,
  [ERROR_CODE.OUT_OF_RANGE]: 400,
  [ERROR_CODE.VALUE_NOT_ALLOWED]: 400,
  [ERROR_CODE.DUPLICATE_VALUE]: 409,

  // Authorization & Authentication
  [ERROR_CODE.UNAUTHORIZED]: 401,
  [ERROR_CODE.INVALID_CREDENTIALS]: 400,
  [ERROR_CODE.MISSING_TOKEN]: 401,
  [ERROR_CODE.EXPIRED_TOKEN]: 401,
  [ERROR_CODE.INVALID_TOKEN]: 401,
  [ERROR_CODE.ACCESS_BLOCKED]: 401,
  [ERROR_CODE.ACCESS_DENIED]: 403,
  [ERROR_CODE.INSUFFICIENT_PERMISSIONS]: 403,
  [ERROR_CODE.ROLE_NOT_ALLOWED]: 403,
  [ERROR_CODE.RESOURCE_FORBIDDEN]: 403,
  [ERROR_CODE.FORBIDDEN]: 403,

  // Resources
  [ERROR_CODE.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODE.RESOURCE_ALREADY_EXISTS]: 409,
  [ERROR_CODE.RESOURCE_LOCKED]: 423,
  [ERROR_CODE.RESOURCE_DISABLED]: 403,
  [ERROR_CODE.RESOURCE_DELETED]: 410,

  // System
  [ERROR_CODE.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODE.SERVICE_TIMEOUT]: 504,
  [ERROR_CODE.DEPENDENCY_FAILURE]: 502,
  [ERROR_CODE.DEPENDENCY_UNAVAILABLE]: 503,
  [ERROR_CODE.RATE_LIMIT_EXCEEDED]: 429,

  // Persistence
  [ERROR_CODE.DATA_READ_ERROR]: 500,
  [ERROR_CODE.DATA_WRITE_ERROR]: 500,
  [ERROR_CODE.DATA_INTEGRITY_ERROR]: 500,
  [ERROR_CODE.DATA_CONSTRAINT_VIOLATION]: 409,
  [ERROR_CODE.DATA_CONFLICT]: 409,

  // Security
  [ERROR_CODE.SECURITY_VIOLATION]: 403,
  [ERROR_CODE.CSRF_DETECTED]: 403,
  [ERROR_CODE.SUSPICIOUS_ACTIVITY]: 403,
  [ERROR_CODE.REQUEST_BLOCKED]: 403,

  // Operations
  [ERROR_CODE.OPERATION_NOT_ALLOWED]: 405,
  [ERROR_CODE.INVALID_OPERATION_STATE]: 400,
  [ERROR_CODE.PRECONDITION_FAILED]: 412,

  // Files
  [ERROR_CODE.FILE_REQUIRED]: 400,
  [ERROR_CODE.FILE_TOO_LARGE]: 413,
  [ERROR_CODE.FILE_TYPE_NOT_ALLOWED]: 415,
  [ERROR_CODE.FILE_UPLOAD_FAILED]: 500,
  [ERROR_CODE.FILE_DELETE_FAILED]: 500,

  // Notifications
  [ERROR_CODE.NOTIFICATION_FAILED]: 500,

  // Session
  [ERROR_CODE.SESSION_EXPIRED]: 401,
  [ERROR_CODE.SESSION_INVALID]: 401,
  [ERROR_CODE.CLIENT_STATE_INVALID]: 400,

  // Environment
  [ERROR_CODE.CONFIG_MISSING]: 500,
  [ERROR_CODE.CONFIG_INVALID]: 500,
  [ERROR_CODE.ENVIRONMENT_ERROR]: 500
}
  `