import type { FilePattern } from "../../types.js"
import { authPrismaSnippet } from './snippets/auth.prisma.Snippet.js'
import * as dep from './common/index.js'



export const prismaBase = (options:FilePattern)=>{
    return[
{
path: `/prisma/schema.prisma`,
file:`${dep.prismaModelPart}
${options.selectedAuth.endsWith('-session')? authPrismaSnippet.schema : ''}
`},
{
path: `/prisma.config.ts`,
file: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`
},
{
  path:`/.env`,
  file: `# Environment variables declared in this file are NOT automatically loaded by Prisma.
# Please add \`import "dotenv/config"\` to your \`prisma.config.ts\` file, or use the Prisma CLI with Bun
# to load environment variables from .env files: https://pris.ly/prisma-config-env-vars.

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB and CockroachDB.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

# The following \`prisma+postgres\` URL is similar to the URL produced by running a local Prisma Postgres
# server with the \`prisma dev\` CLI command, when not choosing any non-default ports or settings. The API key, unlike the
# one found in a remote Prisma Postgres URL, does not contain any sensitive information.

DATABASE_URL="postgres://postgres:password@localhost:5432/dbName"`
},
{
//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//************** Commons files **************//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
path:`/${options.sourceFolderName}/configs/database.ts`,
file: dep.database
},
{
  path:`/${options.sourceFolderName}/shared/repositories/BaseRepository.ts`,
  file: dep.baseRepository
},
{
  path:`/${options.sourceFolderName}/shared/repositories/BaseRepository.test.ts`,
  file: dep.baseRepositoryTest
},
{
  path:`/${options.sourceFolderName}/shared/repositories/testHelpers/testHelp.help.ts`,
  file: dep.baseRepositoryTestHelp
},
{
  path: `/${options.sourceFolderName}/features/user/UserRepository.ts`,
  file: dep.userRepository
}

    ]
}

//${options.sourceFolderName}