import type { FilePattern } from "../../types.js"
import { authPrismaSnippet } from './snippets/auth.prisma.Snippet.js'



export const prismaBase = (options:FilePattern)=>{
    return[
{
path: `/prisma/schema.prisma`,
file:`// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Get a free hosted Postgres database in seconds: \`npx create-db\`

generator client {
  provider = "prisma-client"
  output   = "../generated/prisma"
}

datasource db {
  provider = "postgresql"
}
enum Role {
  ADMIN
  USER
  MODERATOR
}

model User { 
  id       String  @id 
  email    String  @unique
  password String
  nickname String
  name     String
  picture  String
  role     Role @default(USER)
  enabled  Boolean @default(true)
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
} 

 
enum LogLevel {
  DEBUG
  INFO
  WARN
  ERROR
  FATAL
}

model Log {
  id        String    @id
  levelName LogLevel
  levelCode Int
  message   String
  type      String
  stack     String?
  context   String[]
  pid       Int
  time      BigInt
  hostname  String
  keep      Boolean   @default(false)
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}
${options.selectedAuth.endsWith('-session')? authPrismaSnippet.schema : ''}
`},
{
path: `/prisma.config.ts`,
file: `// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
`
},
{
  path:`/.env`,
  file: `# Environment variables declared in this file are NOT automatically loaded by Prisma.
# Please add \`import "dotenv/config"\` to your \`prisma.config.ts\` file, or use the Prisma CLI with Bun
# to load environment variables from .env files: https://pris.ly/prisma-config-env-vars.

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB and CockroachDB.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

# The following \`prisma+postgres\` URL is similar to the URL produced by running a local Prisma Postgres
# server with the \`prisma dev\` CLI command, when not choosing any non-default ports or settings. The API key, unlike the
# one found in a remote Prisma Postgres URL, does not contain any sensitive information.

DATABASE_URL="postgres://postgres:password@localhost:5432/dbName"`
},
{
//^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//************** Commons files **************//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
path:`/${options.sourceFolderName}/configs/database.ts`,
file: `import envConfig from './envConfig.js'
import logger from './logger.js'
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../../generated/prisma/client.js"
import { execSync } from 'child_process'

const connectionString = \`\${envConfig.DatabaseUrl}\`;

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

function getNameDb(dbUri:string):string {
 return dbUri.split('/').slice(-1).join()
}

const startUp = async (reset = false) => {
  try {
    await prisma.$connect()
    const succesmsg = \`🟢 Database \${getNameDb(envConfig.DatabaseUrl)} connected successfully\`

    if (reset === true) {
      // db push usa la URL definida en prisma.config.js (no en schema)
      execSync('npx prisma db push --force-reset', { stdio: 'inherit' })
      logger.info(\`🧪 Database \${getNameDb(envConfig.DatabaseUrl)} cleaned and reset\`)
    }
    await prisma.$connect()
      logger.info(succesmsg)
      console.log(succesmsg)
  } catch (error) {
    logger.error('❌ Error connecting database:', error as any)
    throw error
  }
}

const closeDatabase = async () => {
  try {
// Delay to wait for pending operations (tests)
    await new Promise(res => setTimeout(res, 20))
    await prisma.$disconnect()
    logger.info('🛑 Closing conection database.')
  } catch (error) {
    logger.error('❌ Error closing conection database:', error as any)
    throw error
  }
}

export {
    prisma,
    startUp,
    closeDatabase
}`
},
{
  path:`/${options.sourceFolderName}/shared/repositories/BaseRepository.ts`,
  file:`import type { IBaseRepository, IRepositoryResponse, IPaginatedOptions, IPaginatedResults, Direction } from '../interfaces/base.interface.js'
import { throwError, ERROR_CODE } from '../../configs/errors.js'


export class BaseRepository<
  TDTO,
  TCreate extends Record<string, any>,
  TUpdate = Partial<TCreate>,
  TModel extends {
    findMany: Function
    findUnique: Function
    findFirst: Function
    create: Function
    update: Function
    delete: Function
    count: Function
    name?: string
  } = any
> implements IBaseRepository<TDTO, TCreate, TUpdate> {
  constructor(
    private readonly Model: TModel,
    private readonly parserFn: (model: any) => TDTO,
    private readonly modelName: string = Model.name ?? 'Model',
    private readonly whereField: keyof TDTO & string,
  ) {}

  async getAll(
    field?: unknown,
    whereField?: keyof TDTO | string
  ): Promise<TDTO[]> {
    const whereClause = whereField != null && field != null
  ? { [whereField]: field }
  : {}
    const models = await this.Model.findMany({ where: whereClause })
    return models.map(this.parserFn)
  }

  async getWithPages(
    options?: IPaginatedOptions<TDTO>
  ): Promise<IPaginatedResults<TDTO>> {
    const page = options?.page ?? 1
    const limit = options?.limit ?? 10
    const whereClause = options?.query ?? {}
    const skip = (page - 1) * limit

  const orderClause = options?.order
  ? Object.entries(options.order).map(([field, dir]) => ({
      [field]:
        String(dir).toLowerCase() === 'asc'? 'asc' : 'desc'
    }))
  : { [this.whereField]: 'asc' }

    const data = await this.Model.findMany({
        where: whereClause,
        orderBy: orderClause,
        skip,
        take: limit,
      })
     const total = await this.Model.count({ where: whereClause })
    

    return {
      info: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      },
      data: data.map(this.parserFn)
    }
  }

  async getById(id: string | number): Promise<TDTO> {
    const model = await this.Model.findUnique({ where: { id: id } })
    if (!model) throwError(ERROR_CODE.NOT_FOUND, \`\${this.modelName} not found\`)
    return this.parserFn(model)

  }


  async findByField(
    field: unknown,
    whereField: keyof TDTO | string = this.whereField
  ): Promise<TDTO | null> {
    if (field == null) throwError(ERROR_CODE.REQUIRED_FIELD_MISSING, \`No value provided for \${(whereField as string)}\`)
    const model = await this.Model.findFirst({
      where: { [whereField]: field }
    })
    return model ? this.parserFn(model) : null
  }

  async create(data: TCreate): Promise<TDTO> {
    const model = await this.Model.create({ data })
    return  this.parserFn(model)
  }

  async update(
    id: string | number,
    data: TUpdate
  ): Promise<TDTO> {
    const model = await this.Model.findUnique({ where: { id: id } })
    if (!model) throwError(ERROR_CODE.NOT_FOUND, \`\${this.modelName} not found\`)
    const updated = await this.Model.update({
      where: { id:id },
      data
    })
    return  this.parserFn(updated)
    
  }

  async delete(id: string | number): Promise<string> {
    const model = await this.Model.findUnique({ where: { id: id } })
    if (!model) throwError(ERROR_CODE.NOT_FOUND, \`\${this.modelName} not found\`)
    const value = (model as any)[this.whereField]
    await this.Model.delete({ where: { id: id } })
    return \`\${value} deleted successfully\`
  }
}`
},
{
  path:`/${options.sourceFolderName}/shared/repositories/BaseRepository.test.ts`,
  file:`import { beforeAll, afterAll, describe, it, expect } from 'vitest'
import { startUp, closeDatabase, prisma} from '../../configs/database.ts'
import { BaseRepository } from './BaseRepository.ts'
import * as help from './testHelpers/testHelp.help.ts'


describe('BaseRepository unit test', () => {
  beforeAll(async () => {
    await startUp(true)
  })
  afterAll(async () => {
    await closeDatabase()
  })
  const UserModel = prisma.user
  const test = new BaseRepository(UserModel, help.parser, 'User', 'email')
  describe('Create method', () => {
    it('should create a element', async () => {
      const response = await test.create(help.dataCreate)
      expect(response).toEqual({
        id: expect.any(String),
        email: 'user@email.com',
        password: '123456',
        nickname: 'userTest',
        name: 'user',
        picture: 'https://picsum.photos/200?random=16',
        enabled: true
      })
      help.setStringId(response.id)
    })
  })
  describe('Get methods', () => {
    describe('"getAll" method', () => {
      it('should retrieve an array of elements', async () => {
        await help.createSeedRandomElements(UserModel, help.usersSeed)
        const response = await test.getAll()
        expect(response.length).toBe(16)
      })
      it('Should retrieve an array of elements filtered by query', async () => {
        const response = await test.getAll(false, 'enabled')
        expect(response.length).toBe(3)
      })
    })
    describe('"getById" method', () => {
      it('Should retrieve an element by Id', async () => {
        const response = await test.getById(help.getStringId())
        expect(response).toEqual({
          id: expect.any(String),
          email: 'user@email.com',
          password: '123456',
          nickname: 'userTest',
          name: 'user',
          picture: 'https://picsum.photos/200?random=16',
          enabled: true
        })
      })
    })
    describe('"getByField" method', () => {
      it('Should retrieve an element by field', async () => {
        const response = await test.getByField('user15@email.com', 'email')
        expect(response).toEqual({
          id: expect.any(String),
          email: 'user15@email.com',
          password: '123456',
          nickname: 'userTest15',
          name: 'Fifteen',
          picture: 'https://picsum.photos/200?random=15',
          enabled: expect.any(Boolean)
        })
      })
    })
    describe('"getWithPages" method', () => {
      it('Should retrieve an array of paginated elements', async () => {
        const queryObject = { page: 1, limit: 10,}as const
        const response = await test.getWithPages(queryObject)
        expect(response.info).toEqual({ total: 16, page: 1, limit: 10, totalPages: 2 })
        expect(response.data.length).toBe(10)
        expect(response.data.map(a => a.name)).toEqual(['One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten'])// Order
      })
      it('Should retrieve filtered and sorted elements', async () => {
        const queryObject = { page: 1, limit: 10, query: { enabled: false }, order: { name: 'ASC' } } as const
        const response = await test.getWithPages(queryObject)
        expect(response.info).toEqual({ total: 3, page: 1, limit: 10, totalPages: 1 })
        expect(response.data.length).toBe(3)
        expect(response.data.map(a => a.name)).toEqual(['Fifteen', 'Seven', 'Six'])// Order
      })
    })
  })
  describe('Update method', () => {
    it('should update an element', async () => {
      const data = { name: 'Name of user' }
      const response = await test.update(help.getStringId(), data)
      expect(response).toEqual({
        id: expect.any(String),
        ...help.dataUpdate
      })
    })
  })
  describe('Delete method', () => {
    it('should deleted an element', async () => {
      const response = await test.delete(help.getStringId())
      expect(response).toBe('user@email.com deleted successfully')
    })
  })
})`
},
{
  path:`/${options.sourceFolderName}/shared/repositories/testHelpers/testHelp.help.ts`,
  file:`import type { UserModel } from '../../../../generated/prisma/models/User.js'
import { UuidHandler } from '../../utils/UuidHandler.js'

export interface IUserTest {
  id: string
  email: string
  password: string
  nickname?: string | null
  name: string
  picture?: string | null
  enabled: boolean
}
export interface CreateUserInput {
  id: string
  email: string
  password: string
  nickname?: string | null
  name?: string | null
  picture?: string | null
  enabled: boolean
}
export type UpdateUserInput = Partial<CreateUserInput>

export const parser = (raw: UserModel): IUserTest => {
  return {
    id: raw.id,
    email: raw.email,
    password: raw.password,
    nickname: raw.nickname,
    name: raw.name ?? '',
    picture: raw.picture,
    enabled: raw.enabled
  }
}
export const dataCreate = {
  id: UuidHandler.createUuid(),
  email: 'user@email.com',
  password: '123456',
  nickname: 'userTest',
  name: 'user',
  picture: 'https://picsum.photos/200?random=16'
}
export const dataUpdate: UpdateUserInput = {
  email: 'user@email.com',
  password: '123456',
  nickname: 'userTest',
  name: 'Name of user',
  picture: 'https://picsum.photos/200?random=16',
  enabled: true
}
let stringId:string = ''
export const setStringId = (id:string):void=>{
  stringId = id
}
export const getStringId = ():string =>{
  return stringId
}
//* --------------------------------------------------
// ?          UserSeed
//* ------------------------------------------------
export const createSeedRandomElements = async (model: any, seed: unknown[]) => {
  try {
    if (!seed || seed.length === 0) throw new Error('No data')
    await model.createMany({data: seed})
  } catch (error) {
    console.error('Error createSeedRandomElements: ', error)
  }
}

export const usersSeed = [
  {
    id: UuidHandler.createUuid(),
    email: 'user01@email.com',
    password: '123456',
    nickname: 'userTest01',
    name: 'One',
    picture: 'https://picsum.photos/200?random=1',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user02@email.com',
    password: '123456',
    nickname: 'userTest02',
    name: 'Two',
    picture: 'https://picsum.photos/200?random=2',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user03@email.com',
    password: '123456',
    nickname: 'userTest03',
    name: 'Three',
    picture: 'https://picsum.photos/200?random=3',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user04@email.com',
    password: '123456',
    nickname: 'userTest04',
    name: 'Four',
    picture: 'https://picsum.photos/200?random=4',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user05@email.com',
    password: '123456',
    nickname: 'userTest05',
    name: 'Five',
    picture: 'https://picsum.photos/200?random=5',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user06@email.com',
    password: '123456',
    nickname: 'userTest06',
    name: 'Six',
    picture: 'https://picsum.photos/200?random=6',
    enabled: false
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user07@email.com',
    password: '123456',
    nickname: 'userTest07',
    name: 'Seven',
    picture: 'https://picsum.photos/200?random=7',
    enabled: false
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user08@email.com',
    password: '123456',
    nickname: 'userTest08',
    name: 'Eight',
    picture: 'https://picsum.photos/200?random=8',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user09@email.com',
    password: '123456',
    nickname: 'userTest09',
    name: 'Nine',
    picture: 'https://picsum.photos/200?random=9',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user10@email.com',
    password: '123456',
    nickname: 'userTest10',
    name: 'Ten',
    picture: 'https://picsum.photos/200?random=10',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user11@email.com',
    password: '123456',
    nickname: 'userTest11',
    name: 'Eleven',
    picture: 'https://picsum.photos/200?random=11',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user12@email.com',
    password: '123456',
    nickname: 'userTest12',
    name: 'Twelve',
    picture: 'https://picsum.photos/200?random=12',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user13@email.com',
    password: '123456',
    nickname: 'userTest13',
    name: 'Thirteen',
    picture: 'https://picsum.photos/200?random=13',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user14@email.com',
    password: '123456',
    nickname: 'userTest14',
    name: 'Fourteen',
    picture: 'https://picsum.photos/200?random=14',
    enabled: true
  },
  {
    id: UuidHandler.createUuid(),
    email: 'user15@email.com',
    password: '123456',
    nickname: 'userTest15',
    name: 'Fifteen',
    picture: 'https://picsum.photos/200?random=15',
    enabled: false
  }
]`
},
{
  path: `/${options.sourceFolderName}/features/user/UserRepository.ts`,
  file: `import { prisma } from '../../configs/database.js'
import type { IUserRepository, IUser } from './User.interfaces.js'
import { BaseRepository } from '../../shared/repositories/BaseRepository.js'
import { User, type UserProps } from './User.js'
import type { UserModel } from '../../../generated/prisma/models/User.js'
import { processError, throwError, ERROR_CODE } from '../../configs/errors.js'

const userModel = prisma.user
export class UserRepository implements IUserRepository {
  private base: BaseRepository<UserModel, UserProps, Partial<UserProps>, typeof userModel>

  constructor(){
    this.base = new BaseRepository(userModel, this.mapToRecord, 'User', 'email')
  }

  // ==========================================
  // HELPER: Map from db to user
  // ==========================================
  private mapToRecord(record: UserModel): UserModel {
    return record
  }

  private mapToDomain(record: UserModel): User {
    return new User({
      id: record.id,
      email: record.email,
      password: record.password,
      role: record.role,
      name: record.name,
      nickname: record.nickname,
      picture: record.picture,
      enabled: record.enabled
    })
  }
  private mapToPublic(record: UserModel): IUser {
    return {
      id: record.id,
      email: record.email,
      role: record.role,
      name: record.name,
      nickname: record.nickname,
      picture: record.picture,
      enabled: record.enabled
    }
  }


  // ==========================================
  // BASIC CRUD
  // ==========================================

  async save(userDomain: User): Promise<void> {
    try {
      const data = userDomain.toPersistence()
      const existingUser = await this.base.findByField(data.email, 'email')
      if (existingUser) {
        throwError(ERROR_CODE.DUPLICATE_VALUE, 'This email already exists')
      }
      await this.base.create(data)
    } catch (error) {
      return processError(error, 'Error saving user')
    }
  }

  async getById(id: string): Promise<User | null> {
    try {
      const record = await this.base.getById(id)
      return record ? this.mapToDomain(record) : null
    } catch (error) {
      return processError(error, \`Error searching user id: \${id}\`)
    }
  }
    async getPublicById(id: string): Promise<IUser | null> {
    try {
      const record = await this.base.getById(id)
      return record ? this.mapToPublic(record) : null
    } catch (error) {
      return processError(error, \`Error searching user id: \${id}\`)
    }
  }


  async getAll(): Promise<IUser[]> {
    try {
      const records = await this.base.getAll()
      return records.map(record => this.mapToPublic(record))
    } catch (error) {
      return processError(error, 'Error searching users')
    }
  }
  async update(id:string, userDomain: User):Promise<IUser>{
    try {
      const data = userDomain.toPersistence()
      const updated = await this.base.update(id, data)
      return this.mapToPublic(updated)
    } catch (error) {
      return processError(error, 'Error updating user')
    }

  }

  async delete(id: string): Promise<void> {
    try {
      await this.base.delete(id)
    } catch (error) {
      processError(error, \`Error deleting user \${id}\`)
    }
  }

  // ==========================================
  // ESPECIFIC MÉTHODS
  // ==========================================

  async findByEmail(email: string): Promise<User | null> {
    try {
      const result = await this.base.findByField(email, 'email')
      return result ? this.mapToDomain(result) : null
    } catch (error) {
      return processError(error, \`Error searching user for email \${email}\`)
    }
  }

}`
}

    ]
}

//${options.sourceFolderName}